<html>
<head>
    <meta charset="utf-8">
    <meta name="view-port">
</head>
<body>
    <div class="text-red text-center" style="background-color: #e83e8c;">
        <h1> Hi, ${email}!</h1>
        <br>
        <br>
        <h5 >
            This is your uploaded file:
        </h5>
        <h5>
            ${file}
        </h5>
        <br>
        <h5 style="background-color: #e8da58">
            and that letter was albert Einstein
        </h5>

    </div>
</body>
</html>
